[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build:prod"

[deploy]
startCommand = "npm run start"
# healthcheckPath = "/api/health"
# healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
NODE_ENV = "production"
PORT = 8080

# Performance optimizations
NEXT_SHARP_PATH = "/tmp/node_modules/sharp"
NEXT_TELEMETRY_DISABLED = "1"